Milestone 1: Mobile First
CarlosIgreda/PortfolioSetUpAndMobileFirst pull request #1
Opened 2023-02-18 05:37 UTC by CarlosIgreda

## Portfolio Website Milestone 1: Mobile First

In this milestone I:
•	Created a new branch according to the GitHub flow rules
•	Added a .gitignore file
•	Set up the linters config
•	Used flexbox
•	Created hover effect
•	Created a UI
•	Used images and backgrounds to enhance the look of the website

2023-02-18 06:07 UTC, ABDULALI3468 reviewed
Hi @CarlosIgreda , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media3.giphy.com/media/fS5I4hHyFTu3HnqiZs/giphy.gif"/>

## Invalid Code Review Request

> You have submitted a project, whose README file has a Microverse Logo on Top. Please consider either removing it or replacing it with your own logo only if you have one. Remember its a project requirement to have a standard and professional README.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-18 06:17 UTC, CarlosIgreda commented
Hi @ABDULALI3468. I'm going to remove that Microverse Logo like you suggested to me. Thanks for the feedback and please let me know any other suggestions or advice.

2023-02-18 06:26 UTC, CarlosIgreda commented
Hi again @ABDULALI3468. I updated the README.md file. Please could you give me some feedback about my project Thanks in advance.

2023-02-18 07:20 UTC, ABDULALI3468 commented
> Hi again @ABDULALI3468. I updated the README.md file. Please could you give me some feedback about my project Thanks in advance.

@CarlosIgreda Yes it's looking good now. You can go for the review. But I am seeing that you have closed your Pull Request consider reopening it and using the same PR for the review always for each milestone. In some cases, you can use another PR like the Code Reviewer asked you to it in some certain conditions.

2023-02-18 07:29 UTC, CarlosIgreda commented
Ready @ABDULALI3468 . This PR is reopened.

2023-02-18 09:05 UTC, shella12 requested changes
Hi @CarlosIgreda , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/znopkG3Fd8ki8IuSba/giphy.gif"/>

## Highlights
- All linters passed ✅ 
- Professional README.md ✅   
- clean code ✅ 
- Good commit history ✅ 
- Descriptive pull request ✅ 
- Great use of semantic tags

## Required Changes ♻️

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 09:05 UTC, shella12 commented on index.html
> +                </a>
- [ ] [OPTIONAL] Photographs are not brandable. I would suggest not using your personal photo as a logo. A logo can be an icon, a symbol – perhaps a picture that represents something you sell or a value you stand for. Also, remember that your logo will likely need to be resized depending on where it's being placed; try to use something that looks clear and scalable.

> When photographs are used in logos, they negate the qualities that make for a good, brandable logo design. Photographs can make it more difficult for your audience to identify with your brand and run the risk of making your logo too generic.

2023-02-19 02:27 UTC, CarlosIgreda commented on index.html
> +                </a>
Done @shella12  , I removed the photo.

2023-02-19 02:30 UTC, CarlosIgreda commented on css/main.css
> +}
Done @shella12, I added the "border-bottom-left-radius" like the figma template.

2023-02-19 02:32 UTC, CarlosIgreda commented on css/main.css
> +}
The image that I was using was the mobile version, but I've just updated the content to have the same aspect

2023-02-19 02:34 UTC, CarlosIgreda commented on index.html
> +            </p>
Done @shella12, I made the change and now is <a> tag.

2023-02-19 02:41 UTC, CarlosIgreda commented on css/main.css
> +}
Done @shella12, I added the ```font-weight``` as you suggested to me.

2023-02-19 02:44 UTC, CarlosIgreda commented on css/main.css
> +}
Done @shella12, I made the update for ```gap```.

2023-02-19 02:46 UTC, CarlosIgreda commented on index.html
> +            </h1>
Done @shella12, I put Mariane instead of my name (like the figma template). Also, I updated the ```font-size```.

2023-02-19 02:48 UTC, KanzaTahreem approved these changes
# Approved 🥳

Hi @CarlosIgreda  👋

Great work implementing the changes suggested by the reviewer. You nailed the project 💪 Keep up the great work 🥇

**_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Styling is looking great, perfect!
-  ✅ Great work using the right GitHub Flow 
-  ✅ Commits are descriptive, good work.
-  ✅ Linters are working properly, great job! 
- ✅ Well done implementing the optional suggestion

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-19 03:33 UTC, CarlosIgreda commented
🥳🥳🥳 Thanks for the feedback!

2023-02-19 03:33 UTC, merged